### ISSUE TITLE
SOIC-14 has incorrect rotation

### ISSUE THREAD

**Issue by oxan** [matthewlai/JLCKicadTools#17]
A part with `SOIC-14_3.9x8.7mm_P1.27mm` footprint has incorrect rotation, it needs to be corrected by 270 degrees (like the SOIC-8 and SOIC-18 already in the corrections file). It wouldn't surprise me if all SOIC-* packages need 270 degrees rotation (but I haven't checked that).

**Comment by matthewlai** [comment]
Thanks!
I've set all SOIC-* packages to 270.
