### ISSUE TITLE
Addition of an extra database file

### ISSUE THREAD

**Issue by Shackmeister** [matthewlai/JLCKicadTools#35]
Having an option for an extra database file would be great for personal libraries.
This way I wouldn't need to flood the current database with own namescheme FP's :)

**Comment by matthewlai** [comment]
I am travelling at the moment and don't have kicad set up on my laptop, but can you give this a try?
https://github.com/matthewlai/JLCKicadTools/tree/multiple_databases

You should be able to install with something like:
pip3 install git+https://github.com/matthewlai/JLCKicadTools.git@multiple_databases

**Comment by sophiekovalevsky** [comment]
@matthewlai, I can confirm that https://github.com/matthewlai/JLCKicadTools/commit/8b895dfa05b56ec4dbfd149524c4c436df41d222 works right of the bat, either by setting absolute and relative db paths.

**Comment by matthewlai** [comment]
@sophiekovalevsky Amazing thanks for confirming! I'll merge it.
