### ISSUE TITLE
Components with footprints from my own library do not show up in th ecpl file

### ISSUE THREAD

**Issue by arifainchtein** [matthewlai/JLCKicadTools#50]
Hello,
I did all the steps outlined in your blog and i discovered that all the components that use footprints which i created  do not show up in the cpl file generated.  They do show up in the bom file generated. I am assuming i am missing something in my footprints, but cant figure out what.

Do you have any suggestions?  I am running on OS X
thanks

**Comment by matthewlai** [comment]
Yes, they need to have the SMT flag set.
