### ISSUE TITLE
JLCPCB component placement oddities

### ISSUE THREAD

**Issue by dudanov** [matthewlai/JLCKicadTools#67]
I would like to describe an interesting situation. Maybe someone had experience.
When placing an order, the position of the component SOT-363 appears to be correct.
![partPlacement](https://user-images.githubusercontent.com/10439739/124419722-219d5700-dd6f-11eb-8f74-64dde8e52a46.png)
But in DFM analysis the position is wrong, which is corrected by the JLCPCB engineer.
Before:
![dfm_before](https://user-images.githubusercontent.com/10439739/124419742-2cf08280-dd6f-11eb-9f3d-02319e1fc6cc.png)
After:
![dfm_after](https://user-images.githubusercontent.com/10439739/124419757-32e66380-dd6f-11eb-9e62-7708750aa1d3.png)
It seems to me that DFM analysis should be trusted. So I added the component to the database in #66 .

Actually the question: did I do the right thing and did anyone deal with such oddities?

**Comment by matthewlai** [comment]
I have not seen that before. Will keep an eye!
