### ISSUE TITLE
Using "this folder" as argument

### ISSUE THREAD

**Issue by Shackmeister** [matthewlai/JLCKicadTools#69]
Hi Matthew & Co

Is there a way to run the tool in the current folder?
Perhaps this could be done when no other argument is provided.

Currently I need to use "cd .." and then add the right folder to the tool.
(going one back often brings my PCB repo, hence finding the right folder again can take a while)

**Comment by matthewlai** [comment]
Hello,

Does "." not work? That's what I've always done.

**Comment by Shackmeister** [comment]
That works!
Thanks
