### ISSUE TITLE
Moving requirement for logzero to setup.py

### ISSUE THREAD

**Issue by kroesche** [matthewlai/JLCKicadTools#72]
Thank you for making this tool. It is very useful for generating JLC production files.

Is there a reason you have the two-step install, using pip to install requirements instead of just putting the requirement for `logzero` in the setup.py file? If not, then I would be happy to submit a PR to move this requirement into the setup.py.

**Comment by matthewlai** [comment]
@sophiekovalevsky

**Comment by sophiekovalevsky** [comment]
@matthewlai, thanks to ping, otherwise I couldn't catched. 

@kroesche, there is no particular reason and I think what you brought up is actually a great idea. I would be happy to review your PR.

**Comment by kroesche** [comment]
I submitted PR https://github.com/matthewlai/JLCKicadTools/pull/73
